name: Playwright Tests + Allure + Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🟢 Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 📦 Install dependencies
      - name: Install dependencies
        run: npm ci

      # ⚡ Cache Playwright browsers
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}

      # 🌐 Install only Chromium (faster)
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      # 🧪 Run tests
      - name: Run Playwright tests
        run: npx playwright test

      # 📊 Generate Allure report
      - name: Generate Allure Report
        run: |
          npx allure generate ./allure-results --clean -o ./allure-report

      # 📦 Upload report as artifact
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # 🚀 Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
